@baseurl = http://localhost:8000/api/v1
@token = 330kMPLTQetrveSZ8jyeVeNUt8UgdVW9.m8PCJihfK6yS3S6a61wCSZ/0SDs3woX51FcXnwidWaY=


# @name currentSession
GET {{baseurl}}/sessions/me
Authorization: Bearer {{token}}

###

# @name signup
POST {{baseurl}}/sign-up
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "password123",
  "name": "Admin User"
}

### 

# @name signin
POST {{baseurl}}/sign-in
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "password123"
}

###

# @name userlist
GET {{baseurl}}/users
Authorization: Bearer {{token}}

###

# @name usercreate
POST {{baseurl}}/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "age": 30,
    "password": "password123"
}