@baseurl = http://localhost:8000/api/v1

# @name reference
GET {{baseurl}}/auth/reference

###

# @name home
GET {{baseurl}}

###

# @name sessionsme
GET {{baseurl}}/auth/sessions

###

# @name userlist
GET {{baseurl}}/users

###

# @name usercreate
POST {{baseurl}}/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "age": 30,
    "password": "password123"
}