@baseurl = http://localhost:8000/api/v1
@token = {{signInBetterAuth.response.body.token}}

@agentToken = {{signInBetterAuthAgent.response.body.token}}
@adminToken = {{signInBetterAuthAdmin.response.body.token}}
@customerToken = {{signInBetterAuthCustomer.response.body.token}}

### BETTER AUTH

# @name signUpBetterAuth
POST {{baseurl}}/auth/sign-up/email
Content-Type: application/json

{
  "email": "customer20@test.com",
  "password": "Pass1234",
  "name": "customer 20",
  "phone": "1234567898",
  "birthday": "1990-01-01"
}

### 

# @name signInBetterAuth
POST {{baseurl}}/auth/sign-in/email
Content-Type: application/json

{
  "email": "customerTest@test.com",
  "password": "Pass1234"
}

### 

# @name signInBetterAuthAdmin
POST {{baseurl}}/auth/sign-in/email
Content-Type: application/json

{
  "email": "alidrl@gmail.com",
  "password": "Goodtaste2021.,?"
}

### 

# @name signInBetterAuthAgent
POST {{baseurl}}/auth/sign-in/email
Content-Type: application/json

{
  "email": "agentTest2@test.com",
  "password": "Pass1234"
}

### 

# @name signInBetterAuthCustomer
POST {{baseurl}}/auth/sign-in/email
Content-Type: application/json

{
  "email": "customerTest2@test.com",
  "password": "Pass1234"
}

### 

# @name signOutBetterAuth
POST {{baseurl}}/auth/sign-out
Authorization: Bearer {{token}}


###

# @name userCreateBetterAuth
POST {{baseurl}}/auth/admin/create-user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "officer6@test.com",
  "password": "pass1234",
  "name": "officer 6",
  "phone": "1234567890",
  "birthday": "1990-01-01",
  "role": "officer"
}

###

# @name userUpdateBetterAuth
POST {{baseurl}}/auth/admin/update-user
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

###

# @name listUsersBetterAuth
GET {{baseurl}}/auth/admin/list-users
Authorization: Bearer {{token}}


### BETTER AUTH END


# @name userlist
GET {{baseurl}}/users?
Authorization: Bearer {{adminToken}}

###

# @name userRead
GET {{baseurl}}/users/gFyCpSKP0QbgO19x0eQlFQP3sEE807cc
Authorization: Bearer {{token}}

###

# @name userCreate
POST {{baseurl}}/users
Content-Type: application/json
Authorization: Bearer {{agentToken}}

{
  "name": "customer test 3",
  "email": "customerTest3@test.com",
  "password": "Pass1234",
  "phone": "1234567890",
  "address": "123 Main St",
  "city": "Lusaka",
  "country": "Zambia",
  "birthday": "1990-01-01"
}

### WALLET CONFIGS ###

# @name walletConfigList
GET {{baseurl}}/wallet-configs
Authorization: Bearer {{token}}

### 

# @name walletConfigCreate
POST {{baseurl}}/wallet-configs
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "key": "global",
    "earnRatePercent": 0.01, 
    "expiryMonths": 12,
    "referralBonusReferrer": 5.00,
    "referralBonusReferred": 2.50
}

### CATEGORY ###

# @name categoryList
GET {{baseurl}}/categories
Authorization: Bearer {{token}}

###

# @name categoryDelete
delete {{baseurl}}/categories/3a15306c-10e8-4c4e-8bc4-5e1b7288ae83
Authorization: Bearer {{token}}

###

# @name categoryCreate
POST {{baseurl}}/categories
Authorization: Bearer {{token}}
Content-Type: application/json

{
     "name": "test", "description": "test products"
}
###

# @name categoryUpdate
put {{baseurl}}/categories/7c0c0f3f-ca0b-4d50-a914-18d89c82c303
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "description": "Having 8 types of product"
}

### PRODUCTS ###

# @name productlist
GET {{baseurl}}/products?isActive=true
Authorization: Bearer {{adminToken}}

###

# @name productRead
get {{baseurl}}/products/0ce0acfb-2f0b-4d48-8065-405a08a68b2d
Authorization: Bearer {{token}}

###

# @name productDelete
delete {{baseurl}}/products/3dac08c1-5661-4cf1-88cf-430c42e5e92a
Authorization: Bearer {{token}}

###

# @name productUpdate
put {{baseurl}}/products/c02d2ed9-433a-44e7-b414-e03d0de3d996
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "test"
}

###

# @name productCreate
POST {{baseurl}}/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "categoryId": "51e3a81b-0a0b-4e53-b2e6-87bc556b912c",
    "name": "test product 25KG",
    "description": "test product description",
    "isActive": false,
    "weightKg": 25,
    "price": 250,
    "stockQty": 100,
    "lowStockThreshold": 30
}


### LOYALTY TIERS ###

# @name loyaltyTierList
GET {{baseurl}}/loyalty-tiers
Authorization: Bearer {{token}}


###

# @name loyaltyTierCreate
POST {{baseurl}}/loyalty-tiers
Authorization: Bearer {{token}}
Content-Type: application/json

{
        "name": "Gold",
        "minSpend": 2000,
        "maxSpend": null,
        "color": "#ffd700"
}

### TIER BENEFITS ###

# @name tierBenefitList
GET {{baseurl}}/tier-benefits
Authorization: Bearer {{token}}


###

# @name tierBenefitCreate
POST {{baseurl}}/tier-benefits
Authorization: Bearer {{token}}
Content-Type: application/json

{
"tierId": "15452086-58c4-4ab6-aaa6-be035fc18ec9",
        "description": "Earn 2% back on all purchases + early access to sales + exclusive offers"
}


### VARIANTS END ###

# @name orderList
GET {{baseurl}}/orders
Authorization: Bearer {{customerToken}}

###

# @name orderRead
GET {{baseurl}}/orders/afd39c95-56ac-4f92-8cd9-b0d93d748741
Authorization: Bearer {{agentToken}}

###

# @name previewBasket
POST {{baseurl}}/orders/preview
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "items":[
    {
      "productId": "3f8c9a23-68da-47e6-ad70-380e5aef9ca2",
      "quantity": 1
    },
    {
      "productId": "285bb72c-86fe-4010-8ec6-607c3847546e",
      "quantity": 1
    }
  ]
}

###

# @name orderCreate
POST {{baseurl}}/orders
Authorization: Bearer {{customerToken}}
Content-Type: application/json

{
  "notes": "Please deliver between 9am-5pm",
  "items":[
    {
      "productId": "e9fe9680-7d34-42f4-b949-a123c4876bff",
      "quantity": 2
    },
    {
      "productId": "1ea14da4-6af3-4c42-9901-20e9a5422a10",
      "quantity": 5
    }
  ]
}

### 

# @name orderConfirm
PATCH  {{baseurl}}/orders/af660af4-7234-4cbc-bf68-a21feb3af3ce/confirm
Authorization: Bearer {{agentToken}}

### 

# @name orderDeliver
PATCH  {{baseurl}}/orders/af660af4-7234-4cbc-bf68-a21feb3af3ce/deliver
Authorization: Bearer {{agentToken}}

### 

# @name orderScanQR
POST  {{baseurl}}/orders/scan-qr
Authorization: Bearer {{customerToken}}
Content-Type: application/json

{
  "code": "gt_2c33664b-c6ae-4264-af81-6cac3a6067f0"
}
