@baseurl = http://localhost:8000/api/v1
@token = {{signInBetterAuth.response.body.token}}

@agent1Token = FLVT8CveRZbGnOOEMybLQGbh1cCdvTgg
@customer8Token = OihuQvfKB0h2TNzjRshOSoaLfNr3mmHw

### BETTER AUTH

# @name signUpBetterAuth
POST {{baseurl}}/auth/sign-up/email
Content-Type: application/json

{
  "email": "customer20@test.com",
  "password": "Pass1234",
  "name": "customer 20",
  "phone": "1234567898",
  "birthday": "1990-01-01"
}

### 

# @name signInBetterAuth
POST {{baseurl}}/auth/sign-in/email
Content-Type: application/json

{
  "email": "customer8@test.com",
  "password": "pass1234"
}
### 

# @name signOutBetterAuth
POST {{baseurl}}/auth/sign-out
Authorization: Bearer {{token}}


###

# @name userCreateBetterAuth
POST {{baseurl}}/auth/admin/create-user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "officer6@test.com",
  "password": "pass1234",
  "name": "officer 6",
  "phone": "1234567890",
  "birthday": "1990-01-01",
  "role": "officer"
}

###

# @name userUpdateBetterAuth
POST {{baseurl}}/auth/admin/update-user
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

###

# @name listUsersBetterAuth
GET {{baseurl}}/auth/admin/list-users
Authorization: Bearer {{token}}


### BETTER AUTH END


# @name userlist
GET {{baseurl}}/users?
Authorization: Bearer {{token}}

###

# @name userRead
GET {{baseurl}}/users/gFyCpSKP0QbgO19x0eQlFQP3sEE807cc
Authorization: Bearer {{token}}

###

# @name userCreate
POST {{baseurl}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "customer8",
    "email": "customer8@test.com",
    "password": "pass1234",
    "phone": "1234567890",
    "address": "123 Main St",
    "city": "Lusaka",
    "country": "Zambia",
    "birthday": "1990-01-01"
}

### WALLET CONFIGS ###

# @name walletConfigList
GET {{baseurl}}/wallet-configs
Authorization: Bearer {{token}}

### 

# @name walletConfigCreate
POST {{baseurl}}/wallet-configs
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "key": "global",
    "earnRatePercent": 0.01, 
    "expiryMonths": 12,
    "referralBonusReferrer": 5.00,
    "referralBonusReferred": 2.50
}

### CATEGORY ###

# @name categoryList
GET {{baseurl}}/categories
Authorization: Bearer {{token}}

###

# @name categoryDelete
delete {{baseurl}}/categories/3a15306c-10e8-4c4e-8bc4-5e1b7288ae83
Authorization: Bearer {{token}}

###

# @name categoryCreate
POST {{baseurl}}/categories
Authorization: Bearer {{token}}
Content-Type: application/json

{
     "name": "test", "description": "test products"
}
###

# @name categoryUpdate
put {{baseurl}}/categories/7c0c0f3f-ca0b-4d50-a914-18d89c82c303
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "description": "Having 8 types of product"
}

### PRODUCTS ###

# @name productlist
GET {{baseurl}}/products
Authorization: Bearer {{token}}

###

# @name productRead
get {{baseurl}}/products/0ce0acfb-2f0b-4d48-8065-405a08a68b2d
Authorization: Bearer {{token}}

###

# @name productDelete
delete {{baseurl}}/products/3dac08c1-5661-4cf1-88cf-430c42e5e92a
Authorization: Bearer {{token}}

###

# @name productUpdate
put {{baseurl}}/products/c02d2ed9-433a-44e7-b414-e03d0de3d996
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "test"
}

###

# @name productCreate
POST {{baseurl}}/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "test product",
    "isActive": true,
    "categoryId": "7b84aca4-723a-4e6b-9eb9-28cf558124b7",
    "variants": [
        {
            "weightKg": 25,
            "weightLabel": "25kg",
            "price": 250.00,
            "stockQty": 0,
            "lowStockThreshold": 30
        },
        {
            "weightKg": 50,
            "weightLabel": "50kg",
            "price": 450.00,
            "stockQty": 0,
            "lowStockThreshold": 30
        }
    ]
}


### VARIANTS ###

# @name variantlist
GET {{baseurl}}/variants
?ids=001eb2af-a696-4557-a613-ada1637ad1e7,170b7ff0-5170-483b-8044-731459f9efa5
# ?includeProduct=true
Authorization: Bearer {{token}}

###

# @name variantCreate
post {{baseurl}}/variants
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "weightKg": 25,
    "weightLabel": "25kg",
    "price": 250.00,
    "pointsValue": 2.50,
    "images": ["https://cdn.cloudflare.com/variants/breakfast-25kg.jpg"],
    "stockQty": 0,
    "lowStockThreshold": 30
}


### VARIANTS END ###

### LOYALTY TIERS ###

# @name loyaltyTierList
GET {{baseurl}}/loyalty-tiers
Authorization: Bearer {{token}}


###

# @name loyaltyTierCreate
POST {{baseurl}}/loyalty-tiers
Authorization: Bearer {{token}}
Content-Type: application/json

{
        "name": "Gold",
        "minSpend": 2000,
        "maxSpend": null,
        "color": "#ffd700"
}

### TIER BENEFITS ###

# @name tierBenefitList
GET {{baseurl}}/tier-benefits
Authorization: Bearer {{token}}


###

# @name tierBenefitCreate
POST {{baseurl}}/tier-benefits
Authorization: Bearer {{token}}
Content-Type: application/json

{
"tierId": "15452086-58c4-4ab6-aaa6-be035fc18ec9",
        "description": "Earn 2% back on all purchases + early access to sales + exclusive offers"
}


### VARIANTS END ###

# @name orderList
GET {{baseurl}}/orders
Authorization: Bearer {{token}}

###

# @name orderRead
GET {{baseurl}}/orders/afd39c95-56ac-4f92-8cd9-b0d93d748741
Authorization: Bearer {{agent1Token}}

###

# @name previewBasket
POST {{baseurl}}/orders/preview
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "items":[
    {
      "variantId": "001eb2af-a696-4557-a613-ada1637ad1e7",
      "quantity": 2
    },
    {
      "variantId": "170b7ff0-5170-483b-8044-731459f9efa5",
      "quantity": 1
    }
  ]
}

###

# @name orderCreate
POST {{baseurl}}/orders
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "notes": "Please deliver between 9am-5pm",
  "items":[
    {
      "variantId": "001eb2af-a696-4557-a613-ada1637ad1e7",
      "quantity": 2
    },
    {
      "variantId": "170b7ff0-5170-483b-8044-731459f9efa5",
      "quantity": 1
    }
  ]
}


###

### 

# @name orderConfirm
PATCH  {{baseurl}}/orders/afd39c95-56ac-4f92-8cd9-b0d93d748741/confirm
Authorization: Bearer {{agent1Token}}

### 

# @name orderDeliver
PATCH  {{baseurl}}/orders/afd39c95-56ac-4f92-8cd9-b0d93d748741/deliver
Authorization: Bearer {{agent1Token}}

### 

# @name orderScanQR
POST  {{baseurl}}/orders/scan-qr
Authorization: Bearer {{customer8Token}}
Content-Type: application/json

{
  "code": "gt_e68007a5-cf91-4df0-8151-b014c22f3d02"
}
